version: "3"
services:
  postgres:
    build: postgres/
    image: postgres:latest
    network_mode: bridge
    container_name: postgres

    expose:
      - 6666
    ports:
      - 6666:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=u_learn
    restart: always
    stop_grace_period: 120s
  # APP*****************************************
  