version: "3"
services:
  postgres:
    build: postgres/
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

    ports:
      - "6666:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=u_learn
    restart: always
    stop_grace_period: 120s
  # APP*****************************************
  springbootapp:
    build: app/
    image: springbootapp:latest
    network_mode: bridge
    container_name: springbootapp
    expose:
      - 6667
    ports:
      - 6667:8082
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres-data: