spring:
  main:
        log-startup-info: false
  output:
        ansi:
            enabled: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ulearn-courses-db:6666/u_learn
    username: postgres
    password: root
    continueOnError: true

  jpa:
    hibernate:
     ddl-auto: create-drop
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: info,health
