spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ULearn_cursos_db:5432/ulearn_cursos_db
    username: postgres
    password: root
    continueOnError: true
  flyway:
    baselineOnMigrate: true

  jpa:
    hibernate:
     ddl-auto: validate
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
server:
  port: 8082

